# springdoc:
#   swagger-ui:
#     enabled: true
#     path: /swagger-ui.html
#     config-url: /v3/api-docs/swagger-config
#     urls: 
#       - url: /v3/api-docs
#         name: API Gateway Service
#       - url: /foods/api/v3/api-docs
#         name: FoodItems Service


# spring:
#   cloud:
#     gateway:
#       routes:
#         - id: fooditems-Service
#           uri: http://localhost:8081
#           predicates:
#           - path=/foods/api/**
#           filters:
#           - StripPrefix=2
